[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify"
  edge_functions = "functions"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[functions]
  node_bundler = "esbuild" 